let _array_name_base = [
    //1-16
    "Nameplate",
    "Mr. Astar",
    "Onigiri",
    "Helmet",
    "Dice",
    "Wall Sticker",
    "Token Chest",
    "Diary Book",
    "Fishbowl",
    "Sleeping Bed",
    "Crown",
    "Fortune Statue",
    "Cake",
    "---",
    "---",
    "Door of Travel",
    //17-32
    "Music Box",
    "Straw Hat",
    "Ms. Ether",
    "Window",
    "Cat Cushion",
    "Knit Hat",
    "Pancake",
    "Fluffy House",
    "Picture frame",
    "Flowerpot",
    "Piano",
    "Asnya",
    "Tea Party Set",
    "---",
    "---",
    "Key to Travel",
    //33-48
    "Tablet",
    "Choco Bread",
    "Ribbon",
    "Dr. Bitco",
    "Score Board",
    "Mortarboard",
    "News Board",
    "Light Switch",
    "Rug-Pull",
    "Cuckoo Clock",
    "Lantern",
    "Violin",
    "---",
    "---",
    "---",
    "Travel Bag",
    //49-64
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
];

let _array_name_sp = [
    //193, heart
    "Tiny Heart",
    //194, Ohana Piggy Bank
    "Coin Bank",
    //195, Kusa Pouch
    "Leaf Pouch",
    //196, Cat Mail
    "Cat Mail",
    //197, Nui
    "Coddly Toy",
    //198
    "---",
    //199
    "---",
    //200
    "Present Box",
    //201-212
    "Gray Fluffy",
    "Beige Fluffy",
    "Limegreen Fluffy",
    "Lightblue Fluffy",
    "Blue Fluffy",
    "Purple Fluffy",
    "Redpurple Fluffy",
    "Red Fluffy",
    "Orange Fluffy",
    "Pink Fluffy",
    "Yellow Fluffy",
    "White Fluffy",
    //213-224
    "Gray Fluffier",
    "Beige Fluffier",
    "Limegreen Fluffier",
    "Lightblue Fluffier",
    "Blue Fluffier",
    "Purple Fluffier",
    "Redpurple Fluffier",
    "Red Fluffier",
    "Orange Fluffier",
    "Pink Fluffier",
    "Yellow Fluffier",
    "White Fluffier",
    //225-236
    "Gray Fluffiest",
    "Beige Fluffiest",
    "Limegreen Fluffiest",
    "Lightblue Fluffiest",
    "Blue Fluffiest",
    "Purple Fluffiest",
    "Redpurple Fluffiest",
    "Red Fluffiest",
    "Orange Fluffiest",
    "Pink Fluffiest",
    "Yellow Fluffiest",
    "White Fluffiest",
];

let array_item_name = ["dummy"]; //dummy, 0
array_item_name = array_item_name.concat(_array_name_base);    //common, 1-64
array_item_name = array_item_name.concat(_array_name_base);    //uncommon, 65-128
array_item_name = array_item_name.concat(_array_name_base);    //rare, 129-192
array_item_name = array_item_name.concat(_array_name_sp);      //special, 193-

/*
let array_item_name = [
    //0
    "dummy",
    //1-16
    "Nameplate",
    "Mr. Astar",
    "Dice",
    "Helmet",
    "Sushi",
    "Crown",
    "Ribbon",
    "Window",
    "Knit Hat",
    "Picture Frame",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    //17-32
    "Music Box",
    "Straw Hat",
    "Ms. Ether",
    "Cat Cushion",
    "Uni",
    "Fortune Statue",
    "Asnya",
    "Rug-Pull",
    "Flowerpot",
    "Photo Frame",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    //33-48
    "Tablet",
    "Score Board",
    "Mortarboard",
    "Dr. Bitco",
    "Pancake",
    "Violin",
    "Piano",
    "Light Switch",
    "Lanthanum",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    "(Test Item)",
    //49-64
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    //65-128, uncommon
    //65-80
    "Mr. Astar",
    "Crown",
    "Fortune Statue",
    "Helmet",
    "Nameplate",
    "Ribbon",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    //81-96
    "Flowerpot",
    "Ms. Ether",
    "Straw Hat",
    "Asnya-",
    "Light Switch",
    "Choco. Bread",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    //97-112
    "Violin",
    "Music Box",
    "Dr. Bitco",
    "Dice",
    "Knit Hat",
    "Mortarboard",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    "(Test Item)",
    //113-128
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    //129-192, rare
    "Mr. Astar",
    "Crown",
    "Fortune Statue",
    "Helmet",
    "Nameplate",
    "Ribbon",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    //
    "Flowerpot",
    "Ms. Ether",
    "Straw Hat",
    "Asnya-",
    "Light Switch",
    "Choco. Bread",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    //
    "Violin",
    "Music Box",
    "Dr. Bitco",
    "Dice",
    "Knit Hat",
    "Mortarboard",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    "(Test Item)",
    //
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    //193, heart
    "Tiny Heart",
    //194, Ohana Piggy Bank
    "Ohana Bank",
    //195, Kusa Pouch
    "Kusa Pouch",
    //196, Cat Mail
    "Cat Mail",
    //197, Nui
    "Coddly Toy",
    //198
    "---",
    //199
    "---",
    //200
    "---",
    //201
    "Garnet",
    //202
    "Amethyst",
    //203
    "Aquamarine",
    //204
    "Diamond",
    //205
    "Emerald",
    //206
    "Pearl",
    //207
    "Ruby",
    //208
    "Peridot",
    //209
    "Sapphire",
    //210
    "Opal",
    //211
    "Topaz",
    //212
    "Turquoise",
]
*/