

let _dic_items = {

    //###item_str
    "Nameplate":{
        "item_id":1,
        "item_id_uncommon":1+64,
        "item_id_rare":1+128,
        "img_name":"item_kanban",
        "icon_png":"png/item_kanban4.png",
        "pos_x":85,
        "pos_y":100,
        "scale":0.4,
        "description":"mint a name\n(STR +1)",
    },
    "Mr. Astar":{
        "item_id":2,
        "item_id_uncommon":2+64,
        "item_id_rare":2+128,
        "img_name":"mr_astar_right",
        "icon_png":"icon/mr_astar.png",
        "pos_x":480,
        "pos_y":680,
        "scale":0.12,
        "description":"little housemate",
    },
    "Onigiri":{
        "item_id":3,
        "item_id_uncommon":3+64,
        "item_id_rare":3+128,
        "img_name":"item_food_onigiri",
        "icon_png":"png/item_food_onigiri.png",
        "pos_x":600-35,
        "pos_y":840+10,
        "scale":0.1,
        "description":"looks delicious",
    },
    "Helmet":{
        "item_id":4,
        "item_id_uncommon":4+64,
        "item_id_rare":4+128,
        "img_name":"item_hat_helmet",
        "icon_png":"png/item_hat_helmet.png",
        "pos_x":530,
        "pos_y":255,
        "scale":0.22,
        "description":"wearable hat",
    },
    "Dice":{
        "item_id":5,
        "item_id_uncommon":5+64,
        "item_id_rare":5+128,
        "img_name":"item_dice",
        "icon_png":"png/item_dice.png",
        "pos_x":750,
        "pos_y":600,
        "scale":0.3,
        "description":"daily luck up",
    },
    "Wall Sticker":{
        "item_id":6,
        "item_id_uncommon":6+64,
        "item_id_rare":6+128,
        "img_name":"item_wall_sticker_icon",
        "icon_png":"icon/wall_sticker.png",
        "pos_x":865,
        "pos_y":330,
        "scale":0.4,
        "description":"wall decoration",
    },
    "Token Chest":{
        "item_id":7,
        "item_id_uncommon":7+64,
        "item_id_rare":7+128,
        "img_name":"item_tokenChest",
        "icon_png":"icon/item_tokenChest.png",
        "pos_x":1037,
        "pos_y":600,
        "scale":0.28,
        "description":"tokens inside",
    },
    "Diary Book":{
        "item_id":8,
        "item_id_uncommon":8+64,
        "item_id_rare":8+128,
        "img_name":"item_book",
        "icon_png":"png/item_book.png",
        "pos_x":300,
        "pos_y":570,
        "scale":0.1,
        "description":"histrical parameters",
    },
    "Fishbowl":{
        "item_id":9,
        "item_id_uncommon":9+64,
        "item_id_rare":9+128,
        "img_name":"item_fishbowl_list",
        "icon_png":"png/item_fishbowl.png",
        "pos_x":693,
        "pos_y":148,
        "scale":0.3,
        "description":"growing goldfish",
    },
    "Hammock":{
        "item_id":10,
        "item_id_uncommon":10+64,
        "item_id_rare":10+128,
        "img_name":"item_hammock_list",
        "icon_png":"icon/item_hammock.png",
        "pos_x":1155,
        "pos_y":730,
        "scale":0.8,
        "description":"sleeping when lights out",
    },
    "Crown":{
        "item_id":11,
        "item_id_uncommon":11+64,
        "item_id_rare":11+128,
        "img_name":"item_crown",
        "icon_png":"icon/item_crown.png",
        "pos_x":1050,
        "pos_y":290,
        "scale":0.3,
        "description":"bear decoration",
    },
    "Fortune Statue":{
        "item_id":12,
        "item_id_uncommon":12+64,
        "item_id_rare":12+128,
        "img_name":"item_fortune_statue",
        "icon_png":"png/item_fortune_statue.png",
        "pos_x":486,
        "pos_y":148,
        "scale":0.35,
        "description":"eyes may shine\nin the night...",
    },
    "Cake":{
        "item_id":13,
        "item_id_uncommon":13+64,
        "item_id_rare":13+128,
        "img_name":"item_food_cake",
        "icon_png":"png/item_food_cake.png",
        "pos_x":600+25,
        "pos_y":840-18,
        "scale":0.15,
        "description":"tastes good",
    },
    "Clarinet":{
        "item_id":14,
        "item_id_uncommon":14+64,
        "item_id_rare":14+128,
        "img_name":"item_clarinet",
        "img_name_inactive":"item_clarinet_inactive",
        "icon_png":"png/item_clarinet.png",
    },
    "Horn":{
        "item_id":15,
        "item_id_uncommon":15+64,
        "item_id_rare":15+128,
        "img_name":"item_horn",
        "img_name_inactive":"item_horn_inactive",
        "icon_png":"png/item_horn.png",
    },
    "Door of Travel":{
        "item_id":16,
        "item_id_uncommon":16+64,
        "item_id_rare":16+128,
        "img_name":"icon_clock",
        "icon_png":"icon/icon_clock.png",
    },
    
    //###item_dex
    "Music Box":{
        "item_id":17,
        "item_id_uncommon":17+64,
        "item_id_rare":17+128,
        "img_name":"item_musicbox",
        "icon_png":"icon/item_musicbox.png",
        "pos_x":505,
        "pos_y":370,
        "scale":0.30,
        "description":"play music",
    },
    "Straw Hat":{
        "item_id":18,
        "item_id_uncommon":18+64,
        "item_id_rare":18+128,
        "img_name":"item_hat_mugiwara",
        "icon_png":"png/item_hat_mugiwara.png",
        "pos_x":450,
        "pos_y":255,
        "scale":0.25,
        "description":"wearable hat",
    },
    "Ms. Ether":{
        "item_id":19,
        "item_id_uncommon":19+64,
        "item_id_rare":19+128,
        "img_name":"ms_ether_right",
        "icon_png":"icon/ms_ether.png",
        "pos_x":714,
        "pos_y":685,
        "scale":0.12,
        "description":"little housemate",
    },
    "Window":{
        "item_id":20,
        "item_id_uncommon":20+64,
        "item_id_rare":20+128,
        "img_name":"item_window_day",
        "icon_png":"png/item_window_day.png",
        "pos_x":110,
        "pos_y":225,
        "scale":0.58,
        "description":"wall decoration",
    },
    "Cat Cushion":{
        "item_id":21,
        "item_id_uncommon":21+64,
        "item_id_rare":21+128,
        "img_name":"item_cushion",
        "icon_png":"png/item_cushion.png",
        "pos_x":90,
        "pos_y":620,
        "scale":0.5,
        "description":"a cat will\nsettle down here",
    },
    "Knit Hat":{
        "item_id":22,
        "item_id_uncommon":22+64,
        "item_id_rare":22+128,
        "img_name":"item_hat_knit",
        "icon_png":"png/item_hat_knit.png",
        "pos_x":690,
        "pos_y":255,
        "scale":0.2,
        "description":"wearable hat",
    },
    "Pancake":{
        "item_id":23,
        "item_id_uncommon":23+64,
        "item_id_rare":23+128,
        "img_name":"item_food_pancake",
        "icon_png":"png/item_food_pancake.png",
        "pos_x":600-25,
        "pos_y":840-18,
        "scale":0.2,
        "description":"Yummy",
    },
    "Fluffy House":{
        "item_id":24,
        "item_id_uncommon":24+64,
        "item_id_rare":24+128,
        "img_name":"item_fluffy_house_1",
        "icon_png":"png/item_fluffy_house_1.png",
        "pos_x":250,
        "pos_y":700,
        "scale":0.4,
        "description":"fluffy sticks",
    },
    "Picture Frame":{
        "item_id":25,
        "item_id_uncommon":25+64,
        "item_id_rare":25+128,
        "img_name":"icon_clock",
        "icon_png":"icon/icon_clock.png",
        "pos_x":890,
        "pos_y":300,
        "scale":0.25,
        "description":"display your NFTs",
    },
    "Flowerpot":{
        "item_id":26,
        "item_id_uncommon":26+64,
        "item_id_rare":26+128,
        "img_name":"item_vase",
        "icon_png":"png/item_vase.png",
        "pos_x":865,
        "pos_y":734,
        "scale":0.18,
        "description":"room decoration",
    },
    "Piano":{
        "item_id":27,
        "item_id_uncommon":27+64,
        "item_id_rare":27+128,
        "img_name":"item_piano",
        "img_name_inactive":"item_piano_inactive",
        "icon_png":"icon/item_piano.png",
        "pos_x":595,
        "pos_y":375,
        "scale":0.4,
        "description":"practice the instrument",
    },
    "Asnya":{
        "item_id":28,
        "item_id_uncommon":28+64,
        "item_id_rare":28+128,
        "img_name":"item_asnya",
        "icon_png":"png/item_asnya.png",
        "pos_x":592,
        "pos_y":138,
        "scale":0.25,
        "description":"room decoration",
    },
    "Tea Set":{
        "item_id":29,
        "item_id_uncommon":29+64,
        "item_id_rare":29+128,
        "img_name":"icon_clock",
        "icon_png":"icon/icon_clock.png",
    },
    "Timpani":{
        "item_id":30,
        "item_id_uncommon":30+64,
        "item_id_rare":30+128,
        "img_name":"item_timpani",
        "img_name_inactive":"item_timpani_inactive",
        "icon_png":"png/item_timpani.png",
    },
    "(Item31)":{
        "item_id":31,
        "item_id_uncommon":31+64,
        "item_id_rare":31+128,
        "img_name":"icon_clock",
        "icon_png":"icon/icon_clock.png",
    },
    "Key to Travel":{
        "item_id":32,
        "item_id_uncommon":32+64,
        "item_id_rare":32+128,
        "img_name":"icon_clock",
        "icon_png":"icon/icon_clock.png",
    },
    
    //###item_int
    "Tablet":{
        "item_id":33,
        "item_id_uncommon":33+64,
        "item_id_rare":33+128,
        "img_name":"item_pad_on",
        "icon_png":"png/item_pad_on.png",
        "pos_x":700,
        "pos_y":390,
        "scale":0.25,
        "description":"show status (INT+1)",
    },
    "Choco Bread":{
        "item_id":34,
        "item_id_uncommon":34+64,
        "item_id_rare":34+128,
        "img_name":"item_food_bread",
        "icon_png":"png/item_food_bread.png",
        "pos_x":600+35,
        "pos_y":840+10,
        "scale":0.25,
        "description":"looks taesty (INT+1)",
    },
    "Ribbon":{
        "item_id":35,
        "item_id_uncommon":35+64,
        "item_id_rare":35+128,
        "img_name":"item_ribbon",
        "icon_png":"png/item_ribbon3.png",
        "pos_x":1037,
        "pos_y":401,
        "scale":0.15,
        "description":"bear decoration",
    },
    "Dr. Bitco":{
        "item_id":36,
        "item_id_uncommon":36+64,
        "item_id_rare":36+128,
        "img_name":"dr_bitco_right",
        "icon_png":"icon/dr_bitco.png",
        "pos_x":480,
        "pos_y":680,
        "scale":0.1,
        "description":"little housemate",
    },
    "Score Meter":{
        "item_id":37,
        "item_id_uncommon":37+64,
        "item_id_rare":37+128,
        "img_name":"icon_clock",
        "icon_png":"icon/icon_clock.png",
    },
    "Mortarboard":{
        "item_id":38,
        "item_id_uncommon":38+64,
        "item_id_rare":38+128,
        "img_name":"item_hat_mortarboard",
        "icon_png":"png/item_hat_mortarboard.png",
        "pos_x":610,
        "pos_y":260,
        "scale":0.20,
        "description":"wearable hat",
    },
    "News Board":{
        "item_id":39,
        "item_id_uncommon":39+64,
        "item_id_rare":39+128,
        "img_name":"icon_clock",
        "icon_png":"icon/icon_clock.png",
        "pos_x":110,
        "pos_y":370,
        "scale":0.19,
        "description":"news display",
    },
    "Light Switch":{
        "item_id":40,
        "item_id_uncommon":40+64,
        "item_id_rare":40+128,
        "img_name":"item_switch",
        "icon_png":"icon/item_switch.png",
        "pos_x":1230,
        "pos_y":320,
        "scale":0.25,
        "description":"turn off the light",
    },
    "Rug-Pull":{
        "item_id":41,
        "item_id_uncommon":41+64,
        "item_id_rare":41+128,
        "img_name":"item_rugg",
        "icon_png":"png/item_rugg.png",
        "pos_x":600,
        "pos_y":660,
        "scale":1.7,
        "description":"room decoration",
    },
    "Cuckoo Clock":{
        "item_id":42,
        "item_id_uncommon":42+64,
        "item_id_rare":42+128,
        "img_name":"item_clock",
        "icon_png":"icon/item_clock.png",
        "pos_x":990,
        "pos_y":180,
        "scale":0.45,
        "description":"room decoration",
    },
    "Lantern":{
        "item_id":43,
        "item_id_uncommon":43+64,
        "item_id_rare":43+128,
        "img_name":"item_lantern_list",
        "icon_png":"icon/item_lantern.png",
        "pos_x":230,
        "pos_y":830,
        "scale":0.275,
        "description":"room decoration",
    },
    "Violin":{
        "item_id":44,
        "item_id_uncommon":44+64,
        "item_id_rare":44+128,
        "img_name":"item_violin",
        "img_name_inactive":"item_violin_inactive",
        "icon_png":"png/item_violin.png",
        "pos_x":500,
        "pos_y":650,
        "scale":0.2,
        "description":"practice the instrument",
    },
    "Crayon":{
        "item_id":45,
        "item_id_uncommon":45+64,
        "item_id_rare":45+128,
        "img_name":"icon_clock",
        "icon_png":"icon/icon_clock.png",
        "pos_x":870,
        "pos_y":550,
        "scale":0.2,
        "description":"draw the achievements",
    },
    "Cello":{
        "item_id":46,
        "item_id_uncommon":46+64,
        "item_id_rare":46+128,
        "img_name":"item_cello",
        "img_name_inactive":"item_cello_inactive",
        "icon_png":"png/item_cello.png",
    },
    "(Item47)":{
        "item_id":47,
        "item_id_uncommon":47+64,
        "item_id_rare":47+128,
        "img_name":"icon_clock",
        "icon_png":"icon/icon_clock.png",
    },
    "Travel Bag":{
        "item_id":48,
        "item_id_uncommon":48+64,
        "item_id_rare":48+128,
        "img_name":"icon_clock",
        "icon_png":"icon/icon_clock.png",
    },

    //###special item
    "Coin Bank":{
        "item_id":194,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"item_bank",
        "icon_png":"png/item_bank.png",
        "pos_x":650,
        "pos_y":500,
        "scale":0.275,
        "description":"store coins",
    },
    "Leaf Pouch":{
        "item_id":195,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"item_pouch",
        "icon_png":"png/item_pouch.png",
        "pos_x":550,
        "pos_y":490,
        "scale":0.225,
        "description":"store leaves",
    },
    "Cat Mail":{
        "item_id":196,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"item_mail",
        "icon_png":"icon/mail.png",
        "pos_x":75,
        "pos_y":655,
        "scale":0.6,
        "description":"send a mail\n(cat cushion required)",
    },
    "Fluffy Doll":{
        "item_id":197,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"item_nui",
        "icon_png":"png/item_nui.png",
    },
    "Present Box":{
        "item_id":200,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"item_presentbox_01",
        "icon_png":"png/item_presentbox_01.png",
    },
    
    //###fluffy
    "Gray Fluffy":{
        "item_id":201,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffy_01.png",
        "frame_no":0+10*0,
    },
    "Beige Fluffy":{
        "item_id":202,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffy_02.png",
        "frame_no":0+10*1,
    },
    "Limegreen Fluffy":{
        "item_id":203,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffy_03.png",
        "frame_no":0+10*2,
    },
    "Lightblue Fluffy":{
        "item_id":204,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffy_04.png",
        "frame_no":0+10*3,
    },
    "Blue Fluffy":{
        "item_id":205,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffy_05.png",
        "frame_no":0+10*4,
    },
    "Purple Fluffy":{
        "item_id":206,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffy_06.png",
        "frame_no":0+10*5,
    },
    "Redpurple Fluffy":{
        "item_id":207,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffy_07.png",
        "frame_no":0+10*6,
    },
    "Red Fluffy":{
        "item_id":208,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffy_08.png",
        "frame_no":0+10*7,
    },
    "Orange Fluffy":{
        "item_id":209,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffy_09.png",
        "frame_no":0+10*8,
    },
    "Pink Fluffy":{
        "item_id":210,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffy_10.png",
        "frame_no":0+10*9,
    },
    "Yellow Fluffy":{
        "item_id":211,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffy_11.png",
        "frame_no":0+10*10,
    },
    "White Fluffy":{
        "item_id":212,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffy_12.png",
        "frame_no":0+10*11,
    },
    
    //###fluffier
    "Gray Fluffier":{
        "item_id":201+12,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffier_01.png",
        "frame_no":1+10*0,
    },
    "Beige Fluffier":{
        "item_id":202+12,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffier_02.png",
        "frame_no":1+10*1,
    },
    "Limegreen Fluffier":{
        "item_id":203+12,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffier_03.png",
        "frame_no":1+10*2,
    },
    "Lightblue Fluffier":{
        "item_id":204+12,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffier_04.png",
        "frame_no":1+10*3,
    },
    "Blue Fluffier":{
        "item_id":205+12,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffier_05.png",
        "frame_no":1+10*4,
    },
    "Purple Fluffier":{
        "item_id":206+12,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffier_06.png",
        "frame_no":1+10*5,
    },
    "Redpurple Fluffier":{
        "item_id":207+12,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffier_07.png",
        "frame_no":1+10*6,
    },
    "Red Fluffier":{
        "item_id":208+12,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffier_08.png",
        "frame_no":1+10*7,
    },
    "Orange Fluffier":{
        "item_id":209+12,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffier_09.png",
        "frame_no":1+10*8,
    },
    "Pink Fluffier":{
        "item_id":210+12,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffier_10.png",
        "frame_no":1+10*9,
    },
    "Yellow Fluffier":{
        "item_id":211+12,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffier_11.png",
        "frame_no":1+10*10,
    },
    "White Fluffier":{
        "item_id":212+12,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffier_12.png",
        "frame_no":1+10*11,
    },
    
    //###fluffiest
    "Gray Fluffiest":{
        "item_id":201+24,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffiest_01.png",
        "frame_no":3+10*0,
    },
    "Beige Fluffiest":{
        "item_id":202+24,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffiest_02.png",
        "frame_no":3+10*1,
    },
    "Limegreen Fluffiest":{
        "item_id":203+24,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffiest_03.png",
        "frame_no":3+10*2,
    },
    "Lightblue Fluffiest":{
        "item_id":204+24,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffiest_04.png",
        "frame_no":3+10*3,
    },
    "Blue Fluffiest":{
        "item_id":205+24,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffiest_05.png",
        "frame_no":3+10*4,
    },
    "Purple Fluffiest":{
        "item_id":206+24,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffiest_06.png",
        "frame_no":3+10*5,
    },
    "Redpurple Fluffiest":{
        "item_id":207+24,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffiest_07.png",
        "frame_no":3+10*6,
    },
    "Red Fluffiest":{
        "item_id":208+24,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffiest_08.png",
        "frame_no":3+10*7,
    },
    "Orange Fluffiest":{
        "item_id":209+24,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffiest_09.png",
        "frame_no":3+10*8,
    },
    "Pink Fluffiest":{
        "item_id":210+24,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffiest_10.png",
        "frame_no":3+10*9,
    },
    "Yellow Fluffiest":{
        "item_id":211+24,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffiest_11.png",
        "frame_no":3+10*10,
    },
    "White Fluffiest":{
        "item_id":212+24,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffiest_12.png",
        "frame_no":3+10*11,
    },

    //###doll
    "Gray Doll":{
        "item_id":201+36,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"item_nui_list",
        "icon_png":"icon/doll_01.png",
        "frame_no":0,
    },
    "Beige Doll":{
        "item_id":202+36,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"item_nui_list",
        "icon_png":"icon/doll_02.png",
        "frame_no":1,
    },
    "Limegreen Doll":{
        "item_id":203+36,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"item_nui_list",
        "icon_png":"icon/doll_03.png",
        "frame_no":2,
    },
    "Lightblue Doll":{
        "item_id":204+36,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"item_nui_list",
        "icon_png":"icon/doll_04.png",
        "frame_no":3,
    },
    "Blue Doll":{
        "item_id":205+36,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"item_nui_list",
        "icon_png":"icon/doll_05.png",
        "frame_no":4,
    },
    "Purple Doll":{
        "item_id":206+36,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"item_nui_list",
        "icon_png":"icon/doll_06.png",
        "frame_no":5,
    },
    "Redpurple Doll":{
        "item_id":207+36,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"item_nui_list",
        "icon_png":"icon/doll_07.png",
        "frame_no":6,
    },
    "Red Doll":{
        "item_id":208+36,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"item_nui_list",
        "icon_png":"icon/doll_08.png",
        "frame_no":7,
    },
    "Orange Doll":{
        "item_id":209+36,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"item_nui_list",
        "icon_png":"icon/doll_09.png",
        "frame_no":8,
    },
    "Pink Doll":{
        "item_id":210+36,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"item_nui_list",
        "icon_png":"icon/doll_10.png",
        "frame_no":9,
    },
    "Yellow Doll":{
        "item_id":211+36,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"item_nui_list",
        "icon_png":"icon/doll_11.png",
        "frame_no":10,
    },
    "White Doll":{
        "item_id":212+36,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"item_nui_list",
        "icon_png":"icon/doll_12.png",
        "frame_no":11,
    },
}

let _dic_items_reverse = {};
for (let key in _dic_items) {
    //common
    let _item_id = _dic_items[key]["item_id"];
    _dic_items_reverse[_item_id] = key;
    //uncommon
    let _item_id_uncommon = _dic_items[key]["item_id_uncommon"]
    if (_item_id_uncommon != 0) {
        _dic_items_reverse[_item_id_uncommon] = key;
    }
    //rare
    let _item_id_rare = _dic_items[key]["item_id_rare"]
    if (_item_id_rare != 0) {
        _dic_items_reverse[_item_id_rare] = key;
    }
}


//global
dic_items = _dic_items;
dic_items_reverse = _dic_items_reverse;
