

let _dic_items = {

    //item_str
    "Nameplate":{
        "item_id":1,
        "item_id_uncommon":1+64,
        "item_id_rare":1+128,
        "img_name":"item_kanban",
        "icon_png":"png/item_kanban4.png",
    },
    "Mr. Astar":{
        "item_id":2,
        "item_id_uncommon":2+64,
        "item_id_rare":2+128,
        "img_name":"mr_astar_right",
        "icon_png":"icon/mr_astar.png",
    },
    "Onigiri":{
        "item_id":3,
        "item_id_uncommon":3+64,
        "item_id_rare":3+128,
        "img_name":"item_food_onigiri",
        "icon_png":"png/item_food_onigiri.png",
    },
    "Helmet":{
        "item_id":4,
        "item_id_uncommon":4+64,
        "item_id_rare":4+128,
        "img_name":"item_hat_helmet",
        "icon_png":"png/item_hat_helmet.png",
    },
    "Dice":{
        "item_id":5,
        "item_id_uncommon":5+64,
        "item_id_rare":5+128,
        "img_name":"item_dice",
        "icon_png":"png/item_dice.png",
    },
    "Wall Sticker":{
        "item_id":6,
        "item_id_uncommon":6+64,
        "item_id_rare":6+128,
        "img_name":"item_wall_sticker_icon",
        "icon_png":"icon/wall_sticker.png",
    },
    "Token Chest":{
        "item_id":7,
        "item_id_uncommon":7+64,
        "item_id_rare":7+128,
        "img_name":"item_tokenChest",
        "icon_png":"icon/item_tokenChest.png",
    },
    "Diary Book":{
        "item_id":8,
        "item_id_uncommon":8+64,
        "item_id_rare":8+128,
        "img_name":"item_book",
        "icon_png":"png/item_book.png",
    },
    "Fishbowl":{
        "item_id":9,
        "item_id_uncommon":9+64,
        "item_id_rare":9+128,
        "img_name":"item_fishbowl_list",
        "icon_png":"png/item_fishbowl.png",
    },
    "Hammock":{
        "item_id":10,
        "item_id_uncommon":10+64,
        "item_id_rare":10+128,
        "img_name":"item_hammock_list",
        "icon_png":"icon/item_hammock.png",
    },
    "Crown":{
        "item_id":11,
        "item_id_uncommon":11+64,
        "item_id_rare":11+128,
        "img_name":"item_crown",
        "icon_png":"icon/item_crown.png",
    },
    "Fortune Statue":{
        "item_id":12,
        "item_id_uncommon":12+64,
        "item_id_rare":12+128,
        "img_name":"item_fortune_statue",
        "icon_png":"png/item_fortune_statue.png",
    },
    "Cake":{
        "item_id":13,
        "item_id_uncommon":13+64,
        "item_id_rare":13+128,
        "img_name":"item_food_cake",
        "icon_png":"png/item_food_cake.png",
    },
    "Ukrere":{
        "item_id":14,
        "item_id_uncommon":14+64,
        "item_id_rare":14+128,
        "img_name":"item_ukrere",
        "icon_png":"png/item_ukrere.png",
    },
    "(Item15)":{
        "item_id":15,
        "item_id_uncommon":15+64,
        "item_id_rare":15+128,
        "img_name":"icon_clock",
        "icon_png":"icon/icon_clock.png",
    },
    "Door of Travel":{
        "item_id":16,
        "item_id_uncommon":16+64,
        "item_id_rare":16+128,
        "img_name":"icon_clock",
        "icon_png":"icon/icon_clock.png",
    },
    
    //item_dex
    "Music Box":{
        "item_id":17,
        "item_id_uncommon":17+64,
        "item_id_rare":17+128,
        "img_name":"item_musicbox",
        "icon_png":"icon/item_musicbox.png",
    },
    "Straw Hat":{
        "item_id":18,
        "item_id_uncommon":18+64,
        "item_id_rare":18+128,
        "img_name":"item_hat_mugiwara",
        "icon_png":"png/item_hat_mugiwara.png",
    },
    "Ms. Ether":{
        "item_id":19,
        "item_id_uncommon":19+64,
        "item_id_rare":19+128,
        "img_name":"ms_ether_right",
        "icon_png":"icon/ms_ether.png",
    },
    "Window":{
        "item_id":20,
        "item_id_uncommon":20+64,
        "item_id_rare":20+128,
        "img_name":"item_window_day",
        "icon_png":"png/item_window_day.png",
    },
    "Cat Cushion":{
        "item_id":21,
        "item_id_uncommon":21+64,
        "item_id_rare":21+128,
        "img_name":"item_cushion",
        "icon_png":"png/item_cushion.png",
    },
    "Knit Hat":{
        "item_id":22,
        "item_id_uncommon":22+64,
        "item_id_rare":22+128,
        "img_name":"item_hat_knit",
        "icon_png":"png/item_hat_knit.png",
    },
    "Pancake":{
        "item_id":23,
        "item_id_uncommon":23+64,
        "item_id_rare":23+128,
        "img_name":"item_food_pancake",
        "icon_png":"png/item_food_pancake.png",
    },
    "Fluffy House":{
        "item_id":24,
        "item_id_uncommon":24+64,
        "item_id_rare":24+128,
        "img_name":"item_fluffy_house_1",
        "icon_png":"png/item_fluffy_house_1.png",
    },
    "Picture Frame":{
        "item_id":25,
        "item_id_uncommon":25+64,
        "item_id_rare":25+128,
        "img_name":"icon_clock",
        "icon_png":"icon/icon_clock.png",
    },
    "Flowerpot":{
        "item_id":26,
        "item_id_uncommon":26+64,
        "item_id_rare":26+128,
        "img_name":"item_vase",
        "icon_png":"png/item_vase.png",
    },
    "Piano":{
        "item_id":27,
        "item_id_uncommon":27+64,
        "item_id_rare":27+128,
        "img_name":"item_piano",
        "icon_png":"icon/item_piano.png",
    },
    "Asnya":{
        "item_id":28,
        "item_id_uncommon":28+64,
        "item_id_rare":28+128,
        "img_name":"item_asnya",
        "icon_png":"png/item_asnya.png",
    },
    "Tea Set":{
        "item_id":29,
        "item_id_uncommon":29+64,
        "item_id_rare":29+128,
        "img_name":"icon_clock",
        "icon_png":"icon/icon_clock.png",
    },
    "(Item30)":{
        "item_id":30,
        "item_id_uncommon":30+64,
        "item_id_rare":30+128,
        "img_name":"icon_clock",
        "icon_png":"icon/icon_clock.png",
    },
    "(Item31)":{
        "item_id":31,
        "item_id_uncommon":31+64,
        "item_id_rare":31+128,
        "img_name":"icon_clock",
        "icon_png":"icon/icon_clock.png",
    },
    "Key to Travel":{
        "item_id":32,
        "item_id_uncommon":32+64,
        "item_id_rare":32+128,
        "img_name":"icon_clock",
        "icon_png":"icon/icon_clock.png",
    },
    
    //item_int
    "Tablet":{
        "item_id":33,
        "item_id_uncommon":33+64,
        "item_id_rare":33+128,
        "img_name":"item_pad_on",
        "icon_png":"png/item_pad_on.png",
    },
    "Choco Bread":{
        "item_id":34,
        "item_id_uncommon":34+64,
        "item_id_rare":34+128,
        "img_name":"item_food_bread",
        "icon_png":"png/item_food_bread.png",
    },
    "Ribbon":{
        "item_id":35,
        "item_id_uncommon":35+64,
        "item_id_rare":35+128,
        "img_name":"item_ribbon",
        "icon_png":"png/item_ribbon3.png",
    },
    "Dr. Bitco":{
        "item_id":36,
        "item_id_uncommon":36+64,
        "item_id_rare":36+128,
        "img_name":"dr_bitco_right",
        "icon_png":"icon/dr_bitco.png",
    },
    "Score Meter":{
        "item_id":37,
        "item_id_uncommon":37+64,
        "item_id_rare":37+128,
        "img_name":"icon_clock",
        "icon_png":"icon/icon_clock.png",
    },
    "Mortarboard":{
        "item_id":38,
        "item_id_uncommon":38+64,
        "item_id_rare":38+128,
        "img_name":"item_hat_mortarboard",
        "icon_png":"png/item_hat_mortarboard.png",
    },
    "News Board":{
        "item_id":39,
        "item_id_uncommon":39+64,
        "item_id_rare":39+128,
        "img_name":"icon_clock",
        "icon_png":"icon/icon_clock.png",
    },
    "Light Switch":{
        "item_id":40,
        "item_id_uncommon":40+64,
        "item_id_rare":40+128,
        "img_name":"item_switch",
        "icon_png":"icon/item_switch.png",
    },
    "Rug-Pull":{
        "item_id":41,
        "item_id_uncommon":41+64,
        "item_id_rare":41+128,
        "img_name":"item_rugg",
        "icon_png":"png/item_rugg.png",
    },
    "Cuckoo Clock":{
        "item_id":42,
        "item_id_uncommon":42+64,
        "item_id_rare":42+128,
        "img_name":"item_clock",
        "icon_png":"icon/item_clock.png",
    },
    "Lantern":{
        "item_id":43,
        "item_id_uncommon":43+64,
        "item_id_rare":43+128,
        "img_name":"icon_clock",
        "icon_png":"icon/icon_clock.png",
    },
    "Violin":{
        "item_id":44,
        "item_id_uncommon":44+64,
        "item_id_rare":44+128,
        "img_name":"item_violin",
        "icon_png":"png/item_violin.png",
    },
    "Crayon":{
        "item_id":45,
        "item_id_uncommon":45+64,
        "item_id_rare":45+128,
        "img_name":"icon_clock",
        "icon_png":"icon/icon_clock.png",
    },
    "(Item46)":{
        "item_id":46,
        "item_id_uncommon":46+64,
        "item_id_rare":46+128,
        "img_name":"icon_clock",
        "icon_png":"icon/icon_clock.png",
    },
    "(Item47)":{
        "item_id":47,
        "item_id_uncommon":47+64,
        "item_id_rare":47+128,
        "img_name":"icon_clock",
        "icon_png":"icon/icon_clock.png",
    },
    "Travel Bag":{
        "item_id":48,
        "item_id_uncommon":48+64,
        "item_id_rare":48+128,
        "img_name":"icon_clock",
        "icon_png":"icon/icon_clock.png",
    },

    //special item
    "Coin Bank":{
        "item_id":194,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"item_bank",
        "icon_png":"png/item_bank.png",
    },
    "Leaf Pouch":{
        "item_id":195,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"item_pouch",
        "icon_png":"png/item_pouch.png",
    },
    "Cat Mail":{
        "item_id":196,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"item_mail",
        "icon_png":"icon/mail.png",
    },
    "Fluffy Doll":{
        "item_id":197,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"item_nui",
        "icon_png":"png/item_nui.png",
    },
    "Present Box":{
        "item_id":200,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"item_presentbox_01",
        "icon_png":"png/item_presentbox_01.png",
    },
    
    //fluffy
    "Gray Fluffy":{
        "item_id":201,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffy_01.png",
        "frame_no":0+10*0,
    },
    "Beige Fluffy":{
        "item_id":202,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffy_02.png",
        "frame_no":0+10*1,
    },
    "Limegreen Fluffy":{
        "item_id":203,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffy_03.png",
        "frame_no":0+10*2,
    },
    "Lightblue Fluffy":{
        "item_id":204,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffy_04.png",
        "frame_no":0+10*3,
    },
    "Blue Fluffy":{
        "item_id":205,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffy_05.png",
        "frame_no":0+10*4,
    },
    "Purple Fluffy":{
        "item_id":206,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffy_06.png",
        "frame_no":0+10*5,
    },
    "Redpurple Fluffy":{
        "item_id":207,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffy_07.png",
        "frame_no":0+10*6,
    },
    "Red Fluffy":{
        "item_id":208,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffy_08.png",
        "frame_no":0+10*7,
    },
    "Orange Fluffy":{
        "item_id":209,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffy_09.png",
        "frame_no":0+10*8,
    },
    "Pink Fluffy":{
        "item_id":210,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffy_10.png",
        "frame_no":0+10*9,
    },
    "Yellow Fluffy":{
        "item_id":211,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffy_11.png",
        "frame_no":0+10*10,
    },
    "White Fluffy":{
        "item_id":212,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffy_12.png",
        "frame_no":0+10*11,
    },
    
    //fluffier
    "Gray Fluffier":{
        "item_id":201+12,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffier_01.png",
        "frame_no":1+10*0,
    },
    "Beige Fluffier":{
        "item_id":202+12,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffier_02.png",
        "frame_no":1+10*1,
    },
    "Limegreen Fluffier":{
        "item_id":203+12,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffier_03.png",
        "frame_no":1+10*2,
    },
    "Lightblue Fluffier":{
        "item_id":204+12,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffier_04.png",
        "frame_no":1+10*3,
    },
    "Blue Fluffier":{
        "item_id":205+12,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffier_05.png",
        "frame_no":1+10*4,
    },
    "Purple Fluffier":{
        "item_id":206+12,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffier_06.png",
        "frame_no":1+10*5,
    },
    "Redpurple Fluffier":{
        "item_id":207+12,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffier_07.png",
        "frame_no":1+10*6,
    },
    "Red Fluffier":{
        "item_id":208+12,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffier_08.png",
        "frame_no":1+10*7,
    },
    "Orange Fluffier":{
        "item_id":209+12,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffier_09.png",
        "frame_no":1+10*8,
    },
    "Pink Fluffier":{
        "item_id":210+12,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffier_10.png",
        "frame_no":1+10*9,
    },
    "Yellow Fluffier":{
        "item_id":211+12,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffier_11.png",
        "frame_no":1+10*10,
    },
    "White Fluffier":{
        "item_id":212+12,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffier_12.png",
        "frame_no":1+10*11,
    },
    
    //fluffiest
    "Gray Fluffiest":{
        "item_id":201+24,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffiest_01.png",
        "frame_no":3+10*0,
    },
    "Beige Fluffiest":{
        "item_id":202+24,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffiest_02.png",
        "frame_no":3+10*1,
    },
    "Limegreen Fluffiest":{
        "item_id":203+24,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffiest_03.png",
        "frame_no":3+10*2,
    },
    "Lightblue Fluffiest":{
        "item_id":204+24,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffiest_04.png",
        "frame_no":3+10*3,
    },
    "Blue Fluffiest":{
        "item_id":205+24,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffiest_05.png",
        "frame_no":3+10*4,
    },
    "Purple Fluffiest":{
        "item_id":206+24,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffiest_06.png",
        "frame_no":3+10*5,
    },
    "Redpurple Fluffiest":{
        "item_id":207+24,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffiest_07.png",
        "frame_no":3+10*6,
    },
    "Red Fluffiest":{
        "item_id":208+24,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffiest_08.png",
        "frame_no":3+10*7,
    },
    "Orange Fluffiest":{
        "item_id":209+24,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffiest_09.png",
        "frame_no":3+10*8,
    },
    "Pink Fluffiest":{
        "item_id":210+24,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffiest_10.png",
        "frame_no":3+10*9,
    },
    "Yellow Fluffiest":{
        "item_id":211+24,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffiest_11.png",
        "frame_no":3+10*10,
    },
    "White Fluffiest":{
        "item_id":212+24,
        "item_id_uncommon":0,
        "item_id_rare":0,
        "img_name":"fluffy_fluffys",
        "icon_png":"icon/fluffiest_12.png",
        "frame_no":3+10*11,
    },
}

let _dic_items_reverse = {};
for (let key in _dic_items) {
    //common
    let _item_id = _dic_items[key]["item_id"];
    _dic_items_reverse[_item_id] = key;
    //uncommon
    let _item_id_uncommon = _dic_items[key]["item_id_uncommon"]
    if (_item_id_uncommon != 0) {
        _dic_items_reverse[_item_id_uncommon] = key;
    }
    //rare
    let _item_id_rare = _dic_items[key]["item_id_rare"]
    if (_item_id_rare != 0) {
        _dic_items_reverse[_item_id_rare] = key;
    }
}


//global
dic_items = _dic_items;
dic_items_reverse = _dic_items_reverse;
